# Generated by Django 4.0.4 on 2022-05-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0002_rename_list_filesystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesystem',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
